### ISSUE TITLE
Allow infinite ranges

### ISSUE THREAD

**Issue by mperktold** [franciscotln/callbag-range#3]
This is a feature request to allow creation of infinite pullable sources by making the upper bound optional, or allowing to pass `Infinity`.

Currently, the `checkArgs` function ensures that the output will be a finite range.
However, I think that creating an infinite pullable source does not neccessarily create a problem, and might even be useful in some cases.

On one hand, another operator further down the pipeline such as [`take`](https://github.com/staltz/callbag-take) can be used to avoid infinite loops.

On the other hand, maybe the source is not pulled in a tight loop, but based on user events, like clicking a button. In such a use case, the source really should be infinite, since the number of user events is possibly inifinite as well.

Of course, another option would be to create a separate source factory, maybe something like `infiniteRangeFrom`, but I wanted to open the discussion here first.

**Comment by franciscotln** [comment]
Have you considered `fromIter` with a generator function?
```js
import forEach from "callbag-for-each";
import fromIter from "callbag-from-iter";
import pipe from "callbag-pipe";
import take from "callbag-take";

function* infiniteRange(initialValue) {
  let i = initialValue;
  while (true) yield i++;
}

pipe(
  fromIter(infiniteRange(0)),
  take(5000),
  forEach(x => console.log("new value", x))
);
```
Then you can take as many items as you wish

**Comment by mperktold** [comment]
Actually I haven't, thanks.

Indeed, `fromIter` is quite powerful and can be used for this and for any other pullable synchronous source.
